### ISSUE TITLE
Multiple transition objects

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#10]
Should the API support multiple transition objects? Currently it seems like it might via repeated calls to createTransition(). However, this increases implementation complexity since we need to keep track of every object and ensure that only one can be preparing or transitioning. This is because otherwise it's hard to figure out what should we transition and how.

My proposal is to switch to a singleton like transition something like Document.documentTransition that will have prepare and start, but will always refer to the same object. This means that if a prepare is called while the animation is happening, for example, then we can easily detect this and reject the prepare

**Comment by jeremyroman** [comment]
My intuition is that the document should know about the single transition that's currently active (between prepare and completion) but that multiple callers should be able to keep around transitions with different parameters. You can tell if there's an issue just by checking the document's active transition field, which seems substantially similar in impl complexity

I think you might otherwise have issues where parameters from a previous transition by an unrelated library inadvertently end up used.

But I don't currently have a strongly held feeling.

**Comment by vmpstr** [comment]
That's a good point. It'd be nice to avoid a loop where I try to start the transition and which interferes with whatever a library might be preparing

**Comment by khushalsagar** [comment]
Sounds like this isn't relevant anymore since the API changed to the model mentioned in the first comment. We have a single Document.documentTransition object with prepare/start APIs which rejects prepare calls for transitions that have already started.

This is a good point to keep in mind though, the API should make it obvious that only one transition can be supported at a time. @jakearchibald fyi.
