### ISSUE TITLE
Default animations, and how to override them

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#108]
@khushalsagar in https://github.com/WICG/shared-element-transitions/pull/107/files#r762647572

> This could be a UA detail but we'll need to do a width/height animation instead of changing size through a transform animation if the aspect ratio is different between the 2 images and we don't want the content to stretch as this ratio is changing

We'll want this to be interoperable and predictable, so I think we need to spec it.

My assumption is that the default should avoid animating things which depend on the main thread, particular as page-load is a particularly janky time. Also, transforms give us sub-pixel positioning (top) whereas width & height do not:

https://user-images.githubusercontent.com/93594/144818832-351c2f90-f086-4ddf-9222-0866eb5fe230.mp4

However, if we go with transforms instead, we need to provide a way for the developer to take just the translation part, as they may not want to do the scale part also.  Something like `var()` + custom properties seems like the right model, but it might be weird for the UA to create custom properties. A function like `page-transition-start(scale)` and `page-transition-end(scale)` could work, and expand to many CSS properties. However the [individual transforms](https://drafts.csswg.org/css-transforms-2/#individual-transforms) haven't landed in stable yet. They've been behind a flag for ages.

**Comment by khushalsagar** [comment]
Before we even get to developer overrides, I think even for the UA default behaviour we don't want a transform which changes the content's aspect ratio. I was hoping we could define this by using an object-fit value of cover/contain for the replaced elements. Those should provide the desired behaviour we've seen in most UX explorations : "have the content aligned to the top/center of the box, match the box width and keep the aspect ratio the same. This will either cause the image to clip or letterbox vertically".

For running this in the compositor, I think this could be an internal optimization.

**Comment by flackr** [comment]
> match the box width and keep the aspect ratio the same

FYI, contain only matches the box width if the content doesn't clip. See examples at https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit#result. Are you proposing dynamically choosing the object-fit depending on the size of the content / where it's being placed or do we need a new object-fit value similar to setting background-size: 100%, [example](https://jsbin.com/jitorid/edit?html,css,output).

**Comment by jakearchibald** [comment]
Here's where I think we landed after the meeting. Let me know if I've missed anything:

## Option 1: Animate width & height, and optimise it

The width and height of the container is animated to take the size from its start to end. A transform animation takes care of position, and other elements of transformation such as rotation.

This is really easy to understand and override for developers. It also means that `object-fit` can be used on the images to handle a variety of common cases:

- `cover` - useful when expanding a 4:3 thumbnail to its 16:9 full version.
- `contain` - useful when the element is growing and you want the 'old' element to expand but also be centered within the container.
- `none` - useful when transitioning things like a 1 line heading to a 2 line heading.

The downside to this is animating width and height happens on the main thread. Although layout and paint will hopefully be cheap for these transition elements, page load is a busy time for the main thread, so main thread animations are likely to jank.

We might be able to optimise this and run it on the compositor. However, we'd only be able to optimise certain cases, and it feels likely that developers will unexpectedly fall off the optimised path. It also means advice for animating transition elements will be substantially different to animating other content, where we say "avoid animating layout-triggering properties".

## Option 2: Animate using clip & transforms

- A transform is animated on the container to handle position and scale, but the aspect ratio doesn't change
- A clip path on the container is animated to handle change in aspect ratio
- A translate and scale animation is applied to each image to emulate equivalents to `object-fit`

This doesn't trigger layout, but it still runs on the main thread as we haven't yet optimised animating `clip-path`.

The hope is, in future, this animation will eventually run entirely on the compositor, and avoid any jank from the main thread (although texture uploads may still jank the animation?).

It isn't clear how the developer would select which object-fit equivalent they want for each element.

This is harder to understand than width/height, but still seems relatively easy to override.

## Option 3: Animate using transforms

- A transform is animated on the container to take it from its start position and size to its end position and size.
- The container has `overflow: hidden` to produce clipping
- A translate and scale animation is applied to each image to emulate equivalents to `object-fit`

This animates on the compositor today, although it may still be janked by texture uploads.

The transition animations on the images are likely to be very complex. If the image is to appear to maintain aspect ratio, it'll need a scale animation that counteracts the scaling applied to the container. This gets particularly complicated with non-linear easing.

Overriding parts of this is probably too hard. Developers would probably 'reset' the default styles and start from scratch if they needed something other than the default.

**Comment by khushalsagar** [comment]
I think Option 2 could be a reasonable alternative if we want to make sure these animations are not main thread bound. We can't really use overflow:hidden on the container (in option 3) because we do want shadows in the images to paint outside the container bounds.

Regarding clip-path not being threaded today, there is active working going on to move it to the compositor thread in Chromium that we can rely on. I didn't understand the concern regarding texture uploads here?

Would it be okay to start with option 1 for the origin trial?
- Get data about how often being main thread bound is a cause for jank.
- Understand the ways in which developers override/customize these animations. To make sure the common patterns are easier to set up by overriding the defaults.

Another thought, it'll also be difficult to avoid being main thread bound for the image + style mode where the box decorations have to be repainted as the box size is changing.

**Comment by vmpstr** [comment]
My feeling is that most developers will (eventually?) want to do a mode where they can have a border radius / box shadow on the animating element. In that case, I think we will have to do this on the main thread (right?). This means that option 2 is potentially introducing a performance cliff: it will be fast unless you want to do border radius animation then it's slow, which I guess is better than both things being slow.

How feasible is it for us to "optimize" on the main thread?

**Comment by jakearchibald** [comment]
If the developer wants to make rounded corners + shadows fast, I guess they could use filter + clip path? It isn't straight forward though.

However, it also isn't straight forward if we carve out a fast path that only works in SET + certain conditions. We end up with the developer using familiar CSS but it has different performance rules.

**Comment by khushalsagar** [comment]
We can easily animate visual effects which are not layout inducing (clip-paths, filters, transforms, opacity) off the main thread. But for anything like border which can affect layout, it's very difficult. We *may* be able to set up a paint worklet but it'll have to be limited to certain cases by design since it must not affect layout of any other element.

The current advice to developers is to avoid animating layout inducing properties for the reason that browsers can't accelerate them. We could follow the same advice here. Try to have the defaults animate using accelerated properties. And suggest that developers set up transitions using SET to also only animate those.

If a developer knows that the transition is being initiated at a point where being main thread bound is not an issue, then they can choose to animate other properties. The same that they would do in general.

**Comment by khushalsagar** [comment]
We decided to go with option 1 since it makes for a much more ergonomic API for developers.
