### ISSUE TITLE
Separating the painted area from the layout of images

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#120]
We want the size of a transition image to be the bounding rect of the element it's captured. However, this doesn't always represent the rect of the texture.

In cases where the element is too big, we capture a partial representation, optimising for the area in and around the viewport.

In cases where the element paints outside its bounding box (achievable in many ways in CSS, such as a `box-shadow`, or positioning of children), we want the resulting texture of the transition image to 'overflow' its bounding box.

This isn't currently possible with images on the web. The developer would need to create a wrapper element, and position the image within the wrapper.

### Continue with the workaround

Create a wrapper element, and position the image within it.

This doesn't need anything additional to be added to CSS, but it's pretty rough for developers to understand and manage. @flackr has been pushing for image paint size and replaced content layout size to be independent so developers don't run into this problem.

Possible way to define this:

### Allow developers to define a viewbox for an image

```css
.foo {
  content: view-box(url('./image.png'), 5px, 5px, 300px, 300px);
}
```

`view-box(css-image, min-x, min-y, width, height)`

The `view-box` function takes a CSS image, plus the arguments from [SVG's `viewBox`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox). It returns a viewboxed image.

Positive values for `min-x` and `min-y` means the painting of the image will overflow the top and left of the bounding rect. Negative values mean the painting is offset from the top/left.

If `min-x` + `width` is less than the width of the image, the image will overflow the right of the bounding rect. Similar for `min-y` + `height` and the bottom of the bounding rect.

The `width` and `height` values become the intrinsic size.

A viewboxed image can be used in CSS where an image is used, except in cases where the image is tiled, such as `background-image` and `border-image`, to avoid needing to handle tiles that overlap.

Making this work for `<img>`, will probably need a `viewbox` attribute on `<img>` and `<source>`.

**Comment by flackr** [comment]
While I think content may be the most natural place to express this concept, I realized that [border-image-outset](https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-outset) has very similar behavior to what's being proposed here, in particular it defines how much of the image paints outside of the content box, however it does not extend beyond the border box, [example](https://jsbin.com/bimazuy/edit?html,css,output). It might make sense to try to use a similar pattern or think of this as another box decoration. Some ideas:

1. Extend box-shadow to take a horizontal and vertical spread and a url instead of a color.
   `box-shadow: none|h-offset v-offset blur h-spread v-spread color|image |inset|initial|inherit;`
   Then if we assume the box is 290px x 290px you could express your above example with `box-shadow: -5px -5px 0 10px 10px url('./image.png')`. However, unlike a content property this would imply the image paints below the content. This may not matter for shared element transitions since the element would have no painted content, but if we want to combine this with other box decorations the order may be important, in which case we'd have to define a way for a box shadow to paint above the content.
2. Support images as part of outlines. E.g. this could be something like `outline: 5px url('./image.png')`. This would suggest that the image paints above the content and extends 5px beyond the border-box. However, outline's default paint order is likely to be problematic as it may be above other siblings depending on the browser's chosen painting order per https://www.w3.org/TR/CSS21/zindex.html#painting-order
3. Just use border-image? This may work if the developer is not using box-sizing: border-box, however it's likely not to be flexible enough for cases where you want to add other box decorations and/or use border-box sizing.
4. Apply to content a similar pattern from border-image-outset. E.g. add sizing and outsets to content, perhaps specifically to `<content-replacement>`, allowing for something like `content: url('./image.png') width? height? <length>{1, 4}?` where the 4 lengths are the auto-extended outsets just as in border-image-outset.

Probably option 4 is the most direct, it's very similar to the view-box function you've suggested but makes it a regular part of replaced content.

**Comment by tabatkins** [comment]
First, I understand and support what you're going for here. It seems useful and reasonable. (The core bit of functionality is something I talked about [back in 2010](https://lists.w3.org/Archives/Public/www-style/2010Dec/0327.html).)

However, it's conflating three distinct abilities, which probably need to be separated:

1. What viewBox actually does - shift/scale the coordinate space the image draws in. This has no effect on the size of the image, it just redefines what coordinates the left/top/right/bottom edges of the image correspond to, rather than their default of 0/0/width/height.
2. Change the size of the image - for sizing, aspect-ratio, etc purposes, I presume the result should be treated as width/height in size.
3. Allow the pixels to overflow the image size, at least when not tiled or otherwise limited.

1 and 2 can probably be treated as combined here, because you're "clipping" a segment of the image and it doesn't make much sense to do so and not, at the same time, adjust the size of the image to match the clip. Unsure if we want to call that view-box(), tho. Possibly with an optional third pair of sizes that set the natural width/height of the image to something else? I'd need to think on this a little.

(I was convinced to not put in an explicit function for this, in favor of relying on [media fragments syntax](https://drafts.csswg.org/css-images-4/#image-fragments), but that obviously only works for images with URLs. I'd be fine with adding in an explicit function here.)

3 is a separate bit of functionality tho, and probably something we need to add to each image-using *location* rather than the image *source*, a la the background-repeat:extend idea I linked above. Like @flackr's fourth idea, maybe just applying this to replaced content elements (`img`, things using `content: url()`, etc) would make sense, via properties similar to `object-fit`/`object-position`. Doing so limits the places we need to poke in, and means it works on plain `img` automatically, which is nice.

-----

So, proposal. New properties:

```
Name: object-view-box
Values: none | <length>{4}
Initial: none
...

`object-view-box` takes an x/y/width/height quartet of lengths, and has two effects:

* The object's "natural size" is changed to the specified width and height.
* When rendering into the element, the object is shifted/scaled so that the point (x,y) of the paint is in the top-left of the concrete object size, and the point (x+width, y+height) is in the bottom-right. (`object-fit` and `object-position` determine how the concrete object size is calculated from the natural sizes, and position it. You might be able to see paint outside of the `object-view-box` rectangle, if the other properties make the concrete object size smaller than the element's content box.) 

```
Name: object-overflow
Values: hidden | visible
Initial: hidden
```

By default, replaced elements clip their content to the element's content box. When `object-overflow: visible` is set, then the object's paint can extend outside of the content box. (Using the established stacking order of content vs borders/etc, I assume.)

----

Structuring them this way, as `object-*` properties, means it covers both img elements and the CSS images we care about, and avoids questions about how things like background-repeat work. It also means we only need to define how to extend the painting area once, in a well-defined spot that already knows how to handle overflow. Finally, it means we don't need to carry around additional bounds knowledge with all CSS images and ensure it's retained if you pass it thru additional functions.

**Comment by jakearchibald** [comment]
@tabatkins sold! Yeah, that all works for me.

**Comment by khushalsagar** [comment]
This is resolved now with the addition of object-view-box/object-overflow to the spec for this functionality.
