### ISSUE TITLE
Clarify whether setElement sets it for both captureAndHold and start

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#128]
It's unclear whether we need to do setElement for captureAndHold _and_ separately for start, or is just setting an element sticky for both operations?

**Comment by vmpstr** [comment]
Specifically when something like `#e1` transitions to be `#e2`, what is the expected code?

```js
document.createDocumentTransition(async (t) => {
  t->setElement(e1, "tag");

  await t->captureAndHold();

  // Have to unset e1.
  t->setElement(e1, null);
  // Now set e2 to be the same tag as the captured e1
  t->setElement(e2, "tag");

  t->start();
});
```

That seems awkward. Maybe setting `#e2` to `"tag"` will replace `#e1` as the tagged element? But I think we need to see if that works in all cases, and amend the explainer with this

**Comment by vmpstr** [comment]
A third alternative is to add a function like `clearElements` which would clear the currently set elements

**Comment by vmpstr** [comment]
Undecided, need examples for practical use-cases

**Comment by khushalsagar** [comment]
I ran into an awkward case when tagging elements in script using this API. The set of elements added using transition.setElement(...) in step 1 persist on the object after start(). IIUC the idea was that if the same element just changes style/layout between 2 DOM transitions then you don't need to tag it again in script.

async function startTransition() {
  let transition = document.createDocumentTransition();
  transition.setElement(document.querySelector(".message"), "message");
  transition.start(() => {
    document.querySelector(".message").transform = 'translate(100px)';
  });
}
But if you want to tag a new element on the next page with the same tag then you first need to remove it from the old element using transition.setElement(..) by passing a reference to the old element. This seems silly since the developer would have to retain a reference to the old element. A few options :

1) transition.setElement(nullptr, "foo") clears the tag foo and associated element.

2) Clear the list of elements on |transition| after capture finishes. So the developer needs to tag elements for the start phase again. I think this would be the common scenario. Developers won't realize that we're retaining references to elements from the old DOM on the |transition| object unless they explicitly clear them.

3) Instead of the implicit clear after start above, add an explicit clearElements() API.

Maybe it makes sense to have 1) and 3) for convenience anyway and we should still also do 2).

**Comment by vmpstr** [comment]
We're going to do 2, then I suggest not having 1 or 3, since those would only be used during the same phase as if the script "changed its mind"

**Comment by khushalsagar** [comment]
Yeah, if we're doing 2 then the only time 1 and 3 get used is if script needs to undo something. And technically that can be done with the current API using setElement(element, null);

**Comment by jakearchibald** [comment]
> 2\. Clear the list of elements on |transition| after capture finishes. So the developer needs to tag elements for the start phase again. I think this would be the common scenario.

Are we sure about that?

I think it's common for an element to exist in both StateA and StateB, but should be a shared element in the transition. In which case one `setElement` call is ideal.

I think it's common for an element to exist only in StateA or StateB, and be a shared element in an exist/entry transition. In which case one `setElement` call is ideal.

I think it's common for an element to exist in only StateA, and another to only exist in StateB, but they're conceptually 'the same' and one should transition to the other. In which case `setElement` should be called on each, with the same tag. The element in StateA doesn't need to be unset - it's no longer connected to the document and that's enough.

It seems like we're worried about a different case, where:

- ElementA exists in StateA and StateB
- ElementB exists in StateB
- ElementA should appear to transition to ElementA

That seems pretty unusual to me, or am I missing something?

**Comment by khushalsagar** [comment]
> I think it's common for an element to exist in both StateA and StateB

The exact same element instance? I expect it'll be common to have paired transitions where element A on State A semantically maps to element B on state B so they'd use the same tag. But would it actually be the same element A with different style/layout on state B.

> I think it's common for an element to exist only in StateA or StateB, and be a shared element in an exist/entry transition.
We'd still need a single setElement call in this case. But the downside of retaining state is that we'd be keeping a reference to element A from state A (on DocumentTransition) until the end of the transition unless the developer explicitly clears it after capture finishes.

> The element in StateA doesn't need to be unset - it's no longer connected to the document and that's enough.
But we'd be keeping the DOM tree in memory unnecessarily, no? Even if it has been disconnected from the document.

**Comment by jakearchibald** [comment]
I can't tell if you're agreeing or disagreeing. It sounds like you're questioning it at first, but then you go on to say the same thing.

**Comment by jakearchibald** [comment]
Fwiw, the intent of `setElement` is to behave as close as possible to setting the tag via CSS just for that transition, then removing it afterwards.

**Comment by khushalsagar** [comment]
I just realized only my first response to your comments was in the comment above. :|

You perfectly highlighted the cases we have :

* Same element exists in state A and state B (possibly with a different style/layout) and is a shared element.
* Different elements exist in state A and state B but they're semantically similar so share the same tag.
* An element only exists in state A (exit) or only exists in state B (entry).

Retaining the elements on |documentTransition| allows for only one setElement call in the first case. Every other case involves different elements on each page so you have to do a setElement to tag them anyway.

My worry was that by keeping a reference to the element from state A on |documentTransition| we'll be keeping the DOM element (and it's subtree) alive even after capture. Unless the developer explicitly resets them, and it will be an optimization the developer has to be keep in mind since retaining them won't break functionality.

**Comment by jakearchibald** [comment]
> we'll be keeping the DOM element (and it's subtree) alive even after capture

Why must that be the case, when it isn't the case when setting the tag via CSS?

**Comment by vmpstr** [comment]
I also don't think it's clear in the explainer that doing a setElement(foo, "bar"); is no-op if foo is not connected to the DOM. Or rather, it's a no-op if it's not connected to the DOM at the time when we process these elements, either during capture or start phases.

We should clearly deal with it somehow, but it sounds like this should be a "supported" way of doing things? I think clearing the elements automatically kind of avoids this

**Comment by jakearchibald** [comment]
I see what you mean. Maybe given all this, it's better to just have developers use `el.style.pageTransitionTag` for dynamic tagging. My worry was that folks wouldn't untag stuff because they assume the page is going away, but I guess we could just document that in big red letter 😄

**Comment by khushalsagar** [comment]
setElement is not in the API anymore.
