### ISSUE TITLE
SPA vs MPA focus

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#14]
If it right to focus on the SPA case first? It feels like SPA transitions are already possible, although as you point out there are issues with duplicating the DOM. However, transitions with MPA are not possible at all. Developers that want navigation transitions seem to want them for actual navigations.

**Comment by vmpstr** [comment]
That's a fair point, SPA is easier to implement since it has fewer security implications. We'll do all the PAs :)

**Comment by khushalsagar** [comment]
I'm hoping we can design the API for SPA/MPA together to make sure there are well aligned in terms of the API surface and capabilities supported. But implement and ship the SPA use-case first, since a good chunk of the implementation is already there and we have partners with SPA use-cases as well.

@jakearchibald does that sound reasonable.

**Comment by jakearchibald** [comment]
Yeah, I think that's ok, as long as we're confident that the designed API is shippable for MPA, and actually gets shipped.

**Comment by khushalsagar** [comment]
Great. I'll keep the issue open for now to track and close it once we have an MPA API we're happy with.

**Comment by khushalsagar** [comment]
Tentative MPA API is in the explainer.
