### ISSUE TITLE
Define the paint order for shared elements during a transition.

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#23]
When elements are shared, I think sticking to the analogy that we lift the element, move it to a new spot, and put it back in the page is apt. This means that we paint the shared element on top of others. However, this can also mean that we stop occluding it by other content which otherwise occluded it.

I think that's fine, personally, but I wanted to make sure that we document this.

**Comment by nullhook** [comment]
What happens when a shared element has a will-change prop? Does it need to be reset so the body becomes relative as you're lifting the element on top of the whole page?

What happens if the shared element has a `relative` position and has it's `absolute` children with defined z-index?

I have ran into the above issues. When the cloned element needed to be lifted I had to:

1. reset the will-change prop so body is relative
2. persist stacking order of shared element and it's children

**Comment by vmpstr** [comment]
The shared elements in our API require paint containment, which means that positioned descendants will use this element as the containing block. Other than that, this transition should preserve any z-index ordering inside the element without the need for script to change anything or reset anything. The reason we can do this is that the transition is happening later down the pipeline where we have already fixed the order of all drawing elements.

**Comment by khushalsagar** [comment]
The first comment did mention a few issues about occlusion that we need to define for these transitions:

- The idea that a shared element stops being occluded by other elements on top during the transition sounds reasonable to me. But we should retain the paint order if a shared element was occluded by another shared element?

- How should we decide the order in which elements from old and new state are drawn. Particularly for paired elements, if the stacking order between the elements changes before/after the transition.

**Comment by khushalsagar** [comment]
This is defined in the spec now.
