### ISSUE TITLE
Allow developer to control first paint for new state

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#26]
Our current document-switch timing won't be appropriate for all MPA transition cases.

For example, transitioning from a page with a thumbnail, to a page with the full image (where the image itself moves), would look kinda bad if the full image wasn't loaded.

**Comment by vmpstr** [comment]
That is true, but what to do. We don't want to delay the load of the page because there is a change that we may need to do a transition. After all, the image might not actually be there ever, so we need to animate at some point.

I'm currently papering over this by pretending we have a good pre-renderer and sufficient paint holding such that the first frame of the new page is contentful enough to do some sort of a transition

**Comment by khushalsagar** [comment]
We've discussed making first paint configurable since transitions usually involve async work, we're fetching resources from the network. The SPA case already does this since we blocked painting between prepare finishing and start. The MPA/cross-origin scenario will be difficult to reason about but doable.

**Comment by khushalsagar** [comment]
There are ongoing discussions about a proposal which would allow developers some control over which resources need to be render-blocking. I'll add a link when the explainer is up.

**Comment by khushalsagar** [comment]
Fixed with render-blocking.
