### ISSUE TITLE
Allow low level customization of transition animations 

### ISSUE THREAD

**Issue by pavsidhu** [WICG/shared-element-transitions#28]
The current proposal only has 10 possible transitions. Rather than providing the animations, customisability would allow for more expressive transitions. Perhaps something similar to the web animations API. Like the [Android's fragment transitions](https://developer.android.com/guide/fragments/animate), we could specify animations for the enter and exit animations.

```javascript
document.documentTransition.prepare({
  // The current document fades out to the left
  exitTransition: [
    { transform: 'translateX(0)', opacity: 1 },
    { transform: 'translateX(-100px)', opacity: 0 }
  ],
  // The current document fades in from the right
  enterTransition:  [
    { transform: 'translateX(100px)', opacity: 0 },
    { transform: 'translateX(0)', opacity: 1 }
  ]
});
```

When no transition is provided, the user agent could decide how best to display the transition. Most likely defaulting to OS norms i.e. iOS slide in/out or Android explode/implode.

```javascript
document.documentTransition.prepare();
```

**Comment by mattgperry** [comment]
I strongly agree with this. It also lacks animation options (duration/easing curves etc). I feel like it would be odd not to drive this with WAAPI to benefit from Animation Worklet and other potential developments in this area.

**Comment by ianvollick** [comment]
This was certainly considered, but if we start with UA defaults, we get a number of benefits.
- As mentioned above, the UA can ensure that the transitions are idiomatic on the given OS
- the semantics of the transitions can be consistent (eg, "next" can reliably move in the correct direction considering locale)

These properties of default transitions both help ensure that they are intelligible to users. I also don't think this will close the door on customization. If we start with these defaults (and, as pavsidhu mentioned, these defaults would be needed in any case), we can then gather more information on what experiences are desired, but cannot be expressed.

**Comment by mattgperry** [comment]
If we're leaving it to the UA to ensure idiomatic transitions, why do we allow the use of CSS? Motion and graphic design are one. I don't agree that we should pass some stuff off the the OS and some to the designer.

I don't agree that web specs should start with one-size-fits-all defaults. Web specs are agreed upon and implemented at an absolutely glacial pace. It would be more helpful to start with a low-level API that allows your semantic transitions to be built upon it in userland. Rather than starting with high-level labelled descriptors and, after five years of spec discussions and implementations, start thinking about how to open up the spec to other experiences. Especially when we can see these a mile off (designers will want to design their own transitions)

**Comment by BenjaminDobler** [comment]
I strongly agree with @mattgperry. It is like saying all h1 tags will have a fixed font family and the developer has no chance to change that. I really think a Web spec should open up lots of new possibilities and not lock then into some predefined defaults. With more control this could be really huge if not i am afraid the use cases are quite limited and devs will resort to good old custom FLIP animations for this stuff.

**Comment by khushalsagar** [comment]
Supported in the latest API.
