### ISSUE TITLE
Canceling an in-flight transition before start() is called

### ISSUE THREAD

**Issue by calinoracation** [WICG/shared-element-transitions#30]
I was trying to hook Shared Element Transitions into our router level and called prepare again before calling start() and got a nice error. This was a bug on my end, but also an issue I can foresee being a real one, as we plan on waiting for our new route to fire our internal Time to First Meaningful Paint event before calling `.start()` to ensure the final state has completed rendering.

If a user navigates elsewhere due it taking a while or a new page forgetting to instrument it, for example clicking back or on another link, I don't see a way to cancel the current one, which might have a different rootTransition and shared element list due to a different destination.

Are there any thoughts in implementing support for an AbortSignal or TaskSignal?

**Comment by khushalsagar** [comment]
Thanks for bringing this up. While we do throw an error, the effect of a [prepare, prepare, start] sequence is that the second prepare call cancels the first one. We could specify this in the API to make it clearer.

But your point about having an abort() API in DocumentTransition is a good one. It'll actually make it easier to weed out real bugs vs intentional cancellation. And might give us an opportunity to avoid redundant work in the pipeline.

**Comment by khushalsagar** [comment]
We recently received another feedback which lines up with this feature request. Some sites display a loader screen if the next scene takes a long time to load. So the transition might need to be cancelled depending on whether the site can display the next scene in time or needs to present a loader screen with a different animation and no shared element transition.

**Comment by khushalsagar** [comment]
The abandon() method on SameDocumentTransition supports canceling a transition in progress.
