### ISSUE TITLE
Allow outgoing and incoming transforms on root and shared elements

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#35]
Right now we have "cover-left" which animates-in the new content, and "reveal-in" which animates-out the old content. However, it's pretty common to want to do both at the same time.

It'd be great to split this into "outgoing end transform" and "incoming start transform", where one or both can be set, along with some way to say which should be on top for the animation.

It'd be great if "outgoing end transform" and "incoming start transform" could also be applied to shared elements. I think this would solve https://github.com/WICG/shared-element-transitions/issues/32.

**Comment by khushalsagar** [comment]
I think this feature request is covered in multiple issues :

- Separate animations for root (#31) and shared elements (#37).
- Low level customization of animations as interpolation of properties like transform instead of high level effects (#28).
- Define the paint order of elements during a transition (#23).

Feel free to reopen in case I missed anything.
