### ISSUE TITLE
Dealing with element height 'revealing' in SPAs

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#49]
https://svelte.dev/repl/9b64f0fe79d84395a619f2e65771948d?version=3.42.1 - see the "toggle me" demo half way down the page.

This is a pretty common transition, and almost all instances of it perform layout per frame, and drop frames unless the layout is really basic.

Making this work without layout involves:

- Revealing the element using a `clip-path` (which we currently don't perform on the compositor, but plan to).
- Performing a translate animation on all subsequent elements to slide them down.
- Maybe another `clip-path` animation on the container.

This is really hard to get right. Is this something we'd like to solve with this proposal?

Some things that don't quite fit into the model we're thinking of right now:

- What happens if the user scrolls during the transition?
- What happens if the user toggles the state before the transition is complete?

**Comment by khushalsagar** [comment]
Supporting interactivity during the transition to cancel and reverse it is going to be very difficult. We do need to clarify how we deal with user input during the transition but it's not something we're targeting to support with this API. The primary use-case is navigations between pages. I have been trying to think through what happens if the user hits stop in the browser UI after the transition has started. That's probably the closest parallel to trying to undo a transition in the context of a navigation? And the simplest would be to switch directly to the end state in that case.

For doing this animation, you're right that doing a clip-path is difficult to implement in Chromium today (but on the radar). But you only need it if you want rounded corners to stay during the reveal. We could do a simple clip-rect reveal on the element's snapshot which has the rounded corners baked in. There is also the "pekaboo" text moving to stay in the center as the box size grows which wouldn't work but I assume is okay.

Doing a translate animation on subsequent elements to slide them would work if they are all marked as one shared element. Also if the clip-reveal and translation animation are set up with the same duration/easing curve then the movement will be synchronized.

**Comment by khushalsagar** [comment]
I think the core feature requests for this issue are covered in #47 for clip-path support and #50 for interactivity during transitions. Let's continue the discussion there. Please re-open in case I missed anything.
