### ISSUE TITLE
Defining end of transition to remove pseudo-elements created for the transition.

### ISSUE THREAD

**Issue by khushalsagar** [WICG/shared-element-transitions#64]
A point that came up during design discussions in the [explainer](https://github.com/WICG/shared-element-transitions/blob/new-explainer/explainer.md) was clarifying the event that defines the end of the transition and pseudo-elements created for the transition can be removed. The 2 options are :

- Based on a duration. There is a default UA one but it can be overridden by the developer. The timer starts at the first rendering lifecycle update and the transition completes at this duration.
This is easy to reason about and developers can also do rAF driven animations which are not tied to any browser animation framework (CSS transitions, CSS animations or Web Animations).

- Based on whether an element has an active animation (via the browser animation frameworks mentioned above). Once there is no active animation, the transition completes.
This makes it easy to set up browser animations and have the state be cleaned up automatically. But would end with developers setting no-op animations if they are being rAF driven or there is a delay in fetching stylesheets/script which set up the actual animation.

**Comment by vmpstr** [comment]
I'm fine with not "easily supporting" rAF animations for this. So I think doing the clean up when there are no animations is fine. This is somewhat of an implementation detail, so if someone does use a rAF animation they will be unpleasantly surprised which will likely result in a bug being filed. But that being said, we can always switch to a timer based solution if these cases frequently arise

A side question to this, and I know I've brought this up in other contexts before, but do we need a strict cap on the animation duration?

**Comment by jakearchibald** [comment]
When I was looking at the API proposal my intention was:

- Transition is done when all animations within the animation stage are finished. When an animation finishes, we'd allow the events to fire and the promises to resolve, then check to see if there are any non-finished animations. This would allow animations to chain.
- We wouldn't support raf-based animations in v1 (they're not easy to do for pseudo elements anyway), but we would easily add a way for the developer to provide a promise that settles once the animation is done (similar to `waitUntil` in various APIs).
- There'd be no limit on transition length, since the page is just delaying itself.
