### ISSUE TITLE
If contain:paint or break-inside:avoid is not satisfied, what should happen?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#71]
From the explainer:

Aside from the root, an element offered for a transition has the following restrictions:

- [`contain: paint`](https://developer.mozilla.org/en-US/docs/Web/CSS/contain) which ensures that the element is the containing block for all positioned descendants and generates a stacking context. This implies that the child content will be clipped to the context-box but it can be expanded using ['overflow-clip-margin'](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-clip-margin). Being a stacking context and a containing block allows the element to be treated as a single unit, whereas paint containment simplifies implementation.
- [`break-inside: avoid`](https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside) which disallows fragmentation ensuring the element content is a single rect, i.e., it doesn't break across lines or columns, again allowing the element to be treated as a single unit.

- Open question: If the developer tries to break the above rules, what should happen? Is paint containment applied by the browser? Is that element dropped from the transition? Is the whole transition abandoned?

**Comment by khushalsagar** [comment]
I think it's better for the developer to add this (instead of automatically in the browser) and abandoning the transition if the rule is broken. Makes it obvious when there is an error and avoids abruptly changing the rendering of the element during the transition.

**Comment by vmpstr** [comment]
To clarify, do you mean abandoning the whole transition or excluding elements that violate containment and/or break-inside?

Also to confirm, if there is no break happening inside an element, would we still require break-inside: avoid?

**Comment by khushalsagar** [comment]
I mean abandoning the whole transition. The aim is to make it obvious to the developer that there is an error, right?

"Also to confirm, if there is no break happening inside an element, would we still require break-inside: avoid?". Could there be cases where the break depends on the element's layout on different screen sizes. So you might not see it when testing locally but then happens in production on some user's device. Requiring break-inside:avoid would be more robust if so.

**Comment by khushalsagar** [comment]
The options discussed here were for where paint containment and disallowing fragmentation comes from :

**Implicitly Applied by the Browser**
When an element is marked as a shared element for a transition (via CSS or script API), the browser implicitly adds paint containment and disallows fragmentation for it. This doesn't need to be specified in developer provided CSS applied to the shared element.

_Pros_
- Easier on the developer since it doesn't require changing the element's style to use it as shared. Especially if the element is offered in a script API.

_Cons_
- The element's rendering can change abruptly only for the duration of the transition.
- The element's effective computed style used in subsequent rendering stages will have to depend on inputs outside of the style resolution stage.

**Explicitly Applied by the Developer**
The developer must explicitly add contain: paint and break-inside: avoid to an element before marking it as shared (using a CSS or script API). If this constraint is not satisfied at any point during the transition, it is aborted.

_Pros_
- The constraints required for an element to be shared are explicitly opted-in to by the developer, avoiding unexpected changes.
- The inputs to subsequent rendering stages are consistent with the element's computed style based on developer input.

_Cons_
- If the transition is setup purely in script, it still requires updating the element's style.

We went with the Explicitly Applied by the Developer option since it avoids unintended implicit changes in the element's rendering when an element is used in a transition.

**Comment by khushalsagar** [comment]
This was discussed again at the last sync and the implicit approach was the more preferred one, the pattern has been used with other features as well. We can add a warning to the console to indicate that this is being implicitly applied for better debugging.

**Comment by chrishtr** [comment]
IMO it should be triggered by an HTML attribute or CSS property. Otherwise the state management will be weird.

**Comment by vmpstr** [comment]
I believe we concluded that there should be another property and/or attribute that automatically applies "the right styles" we need. Using that new property is not mandatory, and the developer can specify the required things manually.

This is to ensure that the developer is not surprised by layout changes that can happen as a result of containment and break-inside

**Comment by khushalsagar** [comment]
See text [here](https://tabatkins.github.io/specs/css-shared-element-transitions/#perform-an-outgoing-capture). The transition is aborted if these are not satisfied.
