### ISSUE TITLE
What should happen if v1 API tries to use nested shared elements?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#74]
From the explainer: 

'v1' of this proposal disallows a shared element to be nested inside another shared element.

The restriction avoids the need to preserve the hierarchy of shared elements and associated properties (transform, clip, effects inherited by descendants) in the DOM representation created to render the images referenced above. This helps in minimizing the scope for 'v1' of the feature.

If the developer tries to do this, what should happen, and when is that verified? Is the nested offering ignored? Is the whole transition abandoned?

**Comment by hvanops** [comment]
What happens if we do nothing about this in the API in v1, and a dev tries to use nested shared elements? I think this is a high-priority item, but may have an easy solution -e.g., just ignoring the nested offering.

**Comment by khushalsagar** [comment]
I'll reiterate the rationale for this restriction to make sure we agree with that. Currently we turn nested shared elements into a flat list with no hierarchy. We could do that and add preserving hierarchy as a separate mode (similar to computed style + image vs as a single image). The concern with making a separate mode was that we'll have to continue supporting the 2 modes and all use-cases want the hierarchy mode anyway. By disallowing nesting of shared elements right now, we can add the hierarchy mode later.

But I think we'll likely need the flat list mode as a fallback anyway. @ianvollick made an excellent suggestion that when the hierarchy in the 2 DOM trees has a mismatch, we could fallback to turning them into a flat list. A similar approach is used with transform operations. So I'd be okay with a flat list mode to start with, and adding a hierarchy mode later that a developer can opt-in too.

If we really do want to avoid the 2 modes approach, then the simplest would be to abandon the transition if this happens. We can verify this at the next rendering lifecycle update after the DOM is mutated and abort.

**Comment by vmpstr** [comment]
So the proposal is to turn it into a flat list if they are nested? Maybe we should update the explainer with that then, since it currently says `'v1' of this proposal disallows a shared element to be nested inside another shared element.` That sounds like developers shouldn't do this, but your proposal suggest that developers _can_ do this if they want the hierarchy flattened.

Can you elaborate in which situations a similar approach is used with transform operations?

**Comment by khushalsagar** [comment]
"So the proposal is to turn it into a flat list if they are nested?" : That's what I'm suggesting. The reason the current proposal disallows it is because of the concern mentioned above about having to support a mode which wouldn't be necessary when we do preserve the hierarchy. IMO, a flattened mode is not difficult to support and we'd likely end up needing it for fallback anyway.

For a similar approach with transform operations, consider the case where an element's transform changes from "translateX(10px) rotate(10deg) translateY(5px)" to "perspective(500px)" and it is using a CSS transition. If the number of transform ops is the same, then we do an interpolation on each op in the sequence. But if its not, then we squash the ops into a single matrix and interpolate between 2 matrices. @ianvollick can correct in case I got it wrong.

**Comment by hvanops** [comment]
Ignoring for a sec that flattening the list is a good fallback for when the hierarchy in the 2 DOM trees has a mismatch...
Are there any transitions that can take place that would look worse because it's a flat list than doing no transition at all? Even if we might need to turn it into a flat list for other cases, I want to make sure it's the right thing to do when there are nested elements in v1 as well.

**Comment by khushalsagar** [comment]
"Are there any transitions that can take place that would look worse because it's a flat list than doing no transition at all" : I can't say there is any case where it would look worse than no transition...

Preserving the hierarchy is the right thing in most cases, makes sure the nested content moves with and continues to get clipped by its parent. But if there is no clipping happening during the transition anyway, then it would look fine.

**Comment by ianvollick** [comment]
"So the proposal is to turn it into a flat list if they are nested?" That's not quite what I'd meant. Ideally, we'd have matching topologies before and after and could preserve the topology if that were the case. I was proposing that we flatten only if we have a topology mismatch and this is not possible.

If the ability to preserve hierarchies is added later, and if we start by flattening nested elements in all cases, we'd get a behavior change when support is eventually added. To avoid this, we could drop the transition altogether in the case of nesting.

**Comment by ianvollick** [comment]
...until support for preserving the hierarchy is added, I should say. This raises the question of how to detect support for preserving hierarchies, though.

**Comment by khushalsagar** [comment]
@ianvollick : "we'd get a behavior change when support is eventually added". That's why I was proposing that we treat preserving hierarchy as a separate mode that the developer opts-in to when support is added for it. Similar to "computed style + content image" vs "single image". So we won't change the behaviour for old content which doesn't ask for hierarchy mode.

**Comment by ianvollick** [comment]
Ah, got it. Thank you, I'd missed that line.

**Comment by khushalsagar** [comment]
The question discussed here was that assuming we add functionality which preserves hierarchy of shared elements in the transition DOM in the next version, how do we ensure that this is done in a backwards compatible way :

1) Disallow nested shared elements until this functionality is added.
**Pros**
- preserving hierarchy can eventually be the only mode that needs to be supported.
- can be added incrementally without breaking old content.

**Cons**
- developers will need to ensure they don't use nested shared elements until the functionality is added.
- use-cases which involve nested elements but don't need the hierarchy to be preserved will be unnecessarily blocked.

2) Consider 2 modes : one where nested elements are turned into a flat list in the transition DOM and second where this hierarchy is replicated in the transition DOM. There will be a way to feature detect when second mode is implemented.
**Pros**
- avoids developers to worry about nesting of shared elements in v1 while still allowing the behaviour to change in the next iteration.
- Provides flexibility to not implement the second mode for cross-origin where the implementation needs to be out of process.

**Cons**
- The flat mode will likely never be desirable when hierarchy mode can be supported. So the first mode will become moot.

We went with option 2) to avoid having developers to ensure their shared elements are not nested and the cross-origin ease of implementation.
