### ISSUE TITLE
Compare to Android and other mobile platforms

### ISSUE THREAD

**Issue by domenic** [WICG/shared-element-transitions#8]
Comparing the list of transitions in the readme, namely reveal-*, cover-*, explode, and implode, to the list at https://developer.android.com/training/transitions/start-activity, it seems like fade is missing. Is that intentional?

Similarly, that Android documentation lists four different shared element transition effects, but this proposal doesn't seem to make shared element transitions configurable. Is that intentional?

More generally, I'd love for this repository to do a holistic study of what kinds of transitions are made easy by native platforms. Do iOS, macOS, or Windows have features like this? What kind of transitions do they support? I'd imagine this in some sort of table or listing format.

And, do any platform support user-programmable transitions, or is it all about selecting from a menu like in this proposal?

**Comment by vmpstr** [comment]
Some brief replies below, but I agree that we need to come up with a table or a more comprehensive list of what should or should not be supported.

> Comparing the list of transitions in the readme, namely reveal-_, cover-_, explode, and implode, to the list at https://developer.android.com/training/transitions/start-activity, it seems like fade is missing. Is that intentional?

This was not intentional. I think fade can and should be supported as well.

> Similarly, that Android documentation lists four different shared element transition effects, but this proposal doesn't seem to make shared element transitions configurable. Is that intentional?

This one is a bit tricky. I think the four transitions for elements are, in part, rooted in how android represents activities. For example, changeImageTransform changes the image size and scale type (https://developer.android.com/reference/android/widget/ImageView.ScaleType). However, on the web I think we don't really support the same type of scale type.

Similar with changeBounds and changeClipBounds, which seem very similar when talking about the web. I think it does make sense to think about a couple of different transition effects. Specifically, scaling the image to the new size, or changing the bounds of the container while cross fading the contents. I think for image-type elements scale is the right thing to do. For text content, however, cross-fade with changing clips is the right choice.

Furthermore, I think we need to be a bit careful about supporting too many effects. Specifically, because we would like to support these transitions across origins / pages, we want to avoid effects that would require something like re-raster. Ideally, all of the effects would be able to be accomplished on a texture level, which makes it possible to do the transition without the renderer's involvement (other than producing the frame, obviously). 

Does that make sense?





> More generally, I'd love for this repository to do a holistic study of what kinds of transitions are made easy by native platforms. Do iOS, macOS, or Windows have features like this? What kind of transitions do they support? I'd imagine this in some sort of table or listing format.

I think this is a great idea. I'll get some basics started and we can fill it in over time.

**Comment by domenic** [comment]
This all makes sense; thanks for the prompt response! Looking forward to the results of the investigation.

**Comment by khushalsagar** [comment]
The spec'd API now has the defaults for animating changes in size and position. But its all configurable (similar to other platforms) with existing web platform primitives. Closing this now.
