### ISSUE TITLE
How to specify default transition of root only?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#85]
From the explainer:

Open question: If the developer wants a default animation of the root only, how do they define that?

**Comment by jakearchibald** [comment]
Root is currently different other other offered parts because:

- It's auto-captured if other elements are captured
- It's clipped to viewport
- It uses a special pseudo-reference maybe?

Is there anything else? Because:

- It's auto-captured if other elements are captured - but what if you don't capture other elements? (this issue)
- It's clipped to viewport - but we might need that feature for other elements
- It uses a special pseudo-reference maybe? - but does it need to?

Maybe we shouldn't treat the root differently, and require developers to share them just as they'd share other elements.

```css
:root {
  page-transition-tag: root;
}
```

What if the above was the opt-in? The spec and documentation could recommend using 'root' for the root, but it wouldn't be enforced. The UA stylesheet could include:

```css
:root {
  page-transition-clip: viewport;
}
```

…which could be overridden, or used on other elements.

**Comment by khushalsagar** [comment]
The latest API allows this by setting the tag on the root element. We are clipping the root snapshot to the large viewport but can add an option to change that going forward.
