### ISSUE TITLE
Clarify a replaced element whose content paints outside its bounds.

### ISSUE THREAD

**Issue by khushalsagar** [WICG/shared-element-transitions#99]
The explainer talks about using a replaced element for rendering shared element snapshots with a caveat that the content can paint outside the element bounds. This is not supported for replaced elements currently.

"This would be a replaced element so CSS properties like object-fit will be supported. This element has a width and height of 100%, although the image may paint outside of its own bounds, similar to how a box-shadow is painted outside of an element's bounds."

We need to explain how [sizing algorithms](https://drafts.csswg.org/css-images/#sizing-terms) for properties like object-fit will handle this. IIUC the algorithm uses the specified size on the object to compute the concrete object size. The specified size is what clips the element's content. While in this case we need the content to paint outside this specified size.

**Comment by jakearchibald** [comment]
I guess this is similar to how SVGs can be made to reveal parts outside their viewBox https://static-misc-3.glitch.me/set/ - although this only happens when displaying the SVG in a document context, not in replaced content.

I like how this idea simplifies the sizing of things for developers, but if we're applying this idea to CSS images then I think things get confusing fast when it comes to things like tiled backgrounds.

**Comment by khushalsagar** [comment]
Same as issue #120
